// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgruunildppwjioxxwsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpncnV1bmlsZHBwd2ppb3h4d3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjE0MzEsImV4cCI6MjA1OTg5NzQzMX0.n9Yhyhkh6sassP-Ko20WioB144PJ7nBjV5P1HR7NP7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);